#! /bin/bash

#Archivo de configuraciones de variables globales de todo el proyecto 

#Datos generales del proyecto
#------------------------------------------------------------------------------------
NOMBRE_ORGANIZACION="123"
NOMBRE_SISTEMA="456"
COFIGO_EMPLEADO_AD="AD"






