#! /bin/bash

#Archivo de configuraciones de variables globales de todo el proyecto 

#Datos generales del proyecto
#------------------------------------------------------------------------------------
NOMBRE_ORGANIZACION="Jetsterio"
NOMBRE_SISTEMA="Sistema de Administracion"
COFIGO_EMPLEADO_AD="AD"
GRUPOS_PRINCIPALES=("desarrollo" "infraestructura" "seguridad" "soporte")
